### ISSUE TITLE
Raspberry Pi Compatibility

### ISSUE THREAD

**Issue by neoof86** [grafana/strava-datasource#11]
Hi! 

Just wanted to say this dashboard is great and I have been trying to move my monitoring to a raspberry pi and unfortunately this just doesn't seem to want to work. 

Do you think there will ever be support for this?
I have tried raspbian and Ubuntu server and get the below error when  I try and perform the 2nd verification step

![Screenshot 2020-04-23 at 14 03 32](https://user-images.githubusercontent.com/19991728/80103539-49d6d680-856c-11ea-99b8-211a75442e14.png)

I tried the same account on a fresh version of Ubuntu on the PC and it seems to work 
Any help would be greatly appreciated

**Comment by willianpaixao** [comment]
I stumble upon your issue while having the the same problem.

According to the logs, the plugin fails to start due to lack of a proper binary:
`EROR[04-23|21:14:33] Failed to start plugin logger=plugins.backend pluginId=grafana-strava-datasource error="fork/exec /tmp/grafana-6.7.3/data/plugins/grafana-strava-datasource/dist/strava-plugin_linux_arm: no such file or directory"`

Luckily the fix is easy, on the Makefile we currently have:
https://github.com/grafana/strava-datasource/blob/6a1da8f9e61c329122f9868a47e48293a7435234/Makefile#L34
Adding another make target with the following cross compilation flag would add a binary compatible with the Raspberry Pi's architecture:
`env GOOS=linux GOARCH=arm GOARM=7 go build ...`

@alexanderzobnin how can we proceed to add support?

**Comment by neoof86** [comment]
That’s great @willianpaixao you wouldn’t happen to have the full line of code you would put it and would could maybe test via a pull request??

**Comment by alexanderzobnin** [comment]
Yes, I need to add arm target to the build since it's quite popular.

**Comment by neoof86** [comment]
Thanks @alexanderzobnin you would not happen to have any time lines would you? Just so I dont miss deploying this one its done :) Hope you have a great weekend and week! Again thanks for all the awesome work

**Comment by alexanderzobnin** [comment]
Probably, I'll do some work after Grafana 7.0 release (need to fix compatibility with 7.0), so this will be included in the upcoming release.

**Comment by marcelloceschia** [comment]
I have created a pull request that allows to build it with grafana 7.1 and arm6 support, please give it a try or tell me what to improve

**Comment by alexanderzobnin** [comment]
PR #20 probably fixes this. Not sure about compatibility between ARM versions 6/7, that PR adds support for ARM 6, @neoof86 @willianpaixao what do you think?

**Comment by jontg** [comment]
Looks like arm64 is also missing.... :-) ?

**Comment by jontg** [comment]
```
t=2020-11-01T16:47:52+0000 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=grafana-strava-datasource error="fork/exec /var/lib/grafana/plugins/grafana-strava-datasource/strava-plugin_linux_arm64: no such file or directory"
```

**Comment by alexanderzobnin** [comment]
@jontg yes, we need to add `arm64` too to the build. Thanks for the report!

**Comment by FastHogi** [comment]
@alexanderzobnin Any updates on building an arm64 version, too? I‘m having the same issue here with running Grafana on arm64.

**Comment by alexanderzobnin** [comment]
@FastHogi I'll add ARM64 to the build.
